name: check

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "terraform validate"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate
